// Mock data matching Backend models: examModel, questionModel, submissionModel, resultModel

export const MOCK_EXAMS = {
  current: [
    {
      _id: "exam001",
      title: "Data Structures & Algorithms",
      subject: "CSE-301",
      date: "2025-03-25T10:00:00.000Z",
      duration: 90, // minutes
      totalMarks: 100,
      status: "upcoming",
      instructions: "No calculators. Attempt all sections.",
      teacher: "Dr. Priya Nair",
      questionsCount: 40,
    },
    {
      _id: "exam002",
      title: "Operating Systems Mid-Term",
      subject: "CSE-305",
      date: "2025-03-28T14:00:00.000Z",
      duration: 60,
      totalMarks: 50,
      status: "upcoming",
      instructions: "MCQ only. Negative marking applies.",
      teacher: "Prof. Ramesh Iyer",
      questionsCount: 25,
    },
    {
      _id: "exam003",
      title: "Database Management Systems",
      subject: "CSE-310",
      date: "2025-03-21T09:00:00.000Z",
      duration: 120,
      totalMarks: 100,
      status: "live",
      instructions: "Open-book allowed. Write SQL queries neatly.",
      teacher: "Dr. Sunita Mehta",
      questionsCount: 30,
    },
  ],
  notices: [
    {
      _id: "n001",
      title: "Exam Hall Allocation Released",
      message: "Hall tickets for March 2025 exams are now available. Check the notice board.",
      date: "2025-03-18T08:00:00.000Z",
      priority: "high",
    },
    {
      _id: "n002",
      title: "DBMS Exam Rescheduled",
      message: "The DBMS exam has been rescheduled to March 21, 2025 at 9:00 AM. Please note the change.",
      date: "2025-03-17T12:00:00.000Z",
      priority: "high",
    },
    {
      _id: "n003",
      title: "Practice Test Available",
      message: "A mock test for Data Structures is available on the portal until March 23.",
      date: "2025-03-15T10:00:00.000Z",
      priority: "normal",
    },
  ],
  submitted: [
    {
      _id: "sub001",
      examTitle: "Computer Networks",
      subject: "CSE-308",
      submittedAt: "2025-02-15T12:45:00.000Z",
      totalMarks: 100,
      score: 82,
      status: "graded",
    },
    {
      _id: "sub002",
      examTitle: "Software Engineering",
      subject: "CSE-302",
      submittedAt: "2025-02-08T11:30:00.000Z",
      totalMarks: 75,
      score: 68,
      status: "graded",
    },
    {
      _id: "sub003",
      examTitle: "Theory of Computation",
      subject: "CSE-307",
      submittedAt: "2025-01-25T15:00:00.000Z",
      totalMarks: 100,
      score: null,
      status: "pending",
    },
  ],
};

export const MOCK_RESULTS = [
  {
    _id: "res001",
    examTitle: "Computer Networks",
    subject: "CSE-308",
    date: "2025-02-15T00:00:00.000Z",
    totalMarks: 100,
    scored: 82,
    grade: "A",
    rank: 5,
    classAverage: 71,
    passed: true,
    feedback: "Excellent understanding of network protocols. Work on subnetting.",
  },
  {
    _id: "res002",
    examTitle: "Software Engineering",
    subject: "CSE-302",
    date: "2025-02-08T00:00:00.000Z",
    totalMarks: 75,
    scored: 68,
    grade: "A",
    rank: 3,
    classAverage: 59,
    passed: true,
    feedback: "Good grasp of SDLC. Improve case study answers.",
  },
  {
    _id: "res003",
    examTitle: "Discrete Mathematics",
    subject: "MAT-201",
    date: "2025-01-10T00:00:00.000Z",
    totalMarks: 100,
    scored: 74,
    grade: "B+",
    rank: 12,
    classAverage: 65,
    passed: true,
    feedback: "Good effort. Practice graph theory more.",
  },
  {
    _id: "res004",
    examTitle: "Digital Electronics",
    subject: "CSE-204",
    date: "2024-11-20T00:00:00.000Z",
    totalMarks: 100,
    scored: 91,
    grade: "A+",
    rank: 1,
    classAverage: 72,
    passed: true,
    feedback: "Outstanding performance! Top of the class.",
  },
];
